# -*- coding: utf-8 -*-

from ..vendor import Qt
from ..vendor.Qt import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 201)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinbox_snap_width = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinbox_snap_width.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_snap_width.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinbox_snap_width.setMaximum(9999)
        self.spinbox_snap_width.setObjectName("spinbox_snap_width")
        self.horizontalLayout_5.addWidget(self.spinbox_snap_width)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinbox_snap_height = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinbox_snap_height.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_snap_height.setMaximum(9999)
        self.spinbox_snap_height.setObjectName("spinbox_snap_height")
        self.horizontalLayout_5.addWidget(self.spinbox_snap_height)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.checkbox_snap_active = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkbox_snap_active.setChecked(False)
        self.checkbox_snap_active.setObjectName("checkbox_snap_active")
        self.horizontalLayout_4.addWidget(self.checkbox_snap_active)
        self.checkbox_snap_grid = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkbox_snap_grid.setChecked(True)
        self.checkbox_snap_grid.setObjectName("checkbox_snap_grid")
        self.horizontalLayout_4.addWidget(self.checkbox_snap_grid)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.buttonbox = QtWidgets.QDialogButtonBox(Form)
        self.buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonbox.setObjectName("buttonbox")
        self.gridLayout.addWidget(self.buttonbox, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.spinbox_tab_label_size = QtWidgets.QSpinBox(self.groupBox)
        self.spinbox_tab_label_size.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_tab_label_size.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinbox_tab_label_size.setMaximum(9999)
        self.spinbox_tab_label_size.setObjectName("spinbox_tab_label_size")
        self.horizontalLayout_6.addWidget(self.spinbox_tab_label_size)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.spinbox_tab_height = QtWidgets.QSpinBox(self.groupBox)
        self.spinbox_tab_height.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_tab_height.setMaximum(9999)
        self.spinbox_tab_height.setObjectName("spinbox_tab_height")
        self.horizontalLayout_6.addWidget(self.spinbox_tab_height)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(Qt.QtCompat.translate("Form", "Form", None, -1))
        self.groupBox_2.setTitle(Qt.QtCompat.translate("Form", "snap", None, -1))
        self.label_7.setText(Qt.QtCompat.translate("Form", "Width", None, -1))
        self.label_6.setText(Qt.QtCompat.translate("Form", "Height", None, -1))
        self.checkbox_snap_active.setText(Qt.QtCompat.translate("Form", "Active", None, -1))
        self.checkbox_snap_grid.setText(Qt.QtCompat.translate("Form", "Guide grid", None, -1))
        self.groupBox.setTitle(Qt.QtCompat.translate("Form", "Tab", None, -1))
        self.label_8.setText(Qt.QtCompat.translate("Form", "FontSize", None, -1))
        self.label_9.setText(Qt.QtCompat.translate("Form", "Height", None, -1))

