# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\owner\Documents\Github\SiShelf\gui\partition_setting.ui'
#
# Created: Sun Apr 09 06:02:21 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(556, 258)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonbox = QtGui.QDialogButtonBox(Form)
        self.buttonbox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonbox.setObjectName("buttonbox")
        self.gridLayout.addWidget(self.buttonbox, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.button_preview = QtGui.QHBoxLayout()
        self.button_preview.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.button_preview.setObjectName("button_preview")
        self.horizontalLayout_9.addLayout(self.button_preview)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinbox_btn_position_x = QtGui.QSpinBox(self.groupBox_2)
        self.spinbox_btn_position_x.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_btn_position_x.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinbox_btn_position_x.setMaximum(9999)
        self.spinbox_btn_position_x.setObjectName("spinbox_btn_position_x")
        self.horizontalLayout_5.addWidget(self.spinbox_btn_position_x)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinbox_btn_position_y = QtGui.QSpinBox(self.groupBox_2)
        self.spinbox_btn_position_y.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_btn_position_y.setMaximum(9999)
        self.spinbox_btn_position_y.setObjectName("spinbox_btn_position_y")
        self.horizontalLayout_5.addWidget(self.spinbox_btn_position_y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinbox_line_length = QtGui.QSpinBox(self.groupBox_2)
        self.spinbox_line_length.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_line_length.setMaximum(9999)
        self.spinbox_line_length.setObjectName("spinbox_line_length")
        self.horizontalLayout_2.addWidget(self.spinbox_line_length)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.spinbox_line_width = QtGui.QSpinBox(self.groupBox_2)
        self.spinbox_line_width.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_line_width.setMaximum(9999)
        self.spinbox_line_width.setObjectName("spinbox_line_width")
        self.horizontalLayout_8.addWidget(self.spinbox_line_width)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.combo_style = QtGui.QComboBox(self.groupBox_2)
        self.combo_style.setObjectName("combo_style")
        self.combo_style.addItem("")
        self.combo_style.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_style)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinbox_label_font_size = QtGui.QSpinBox(self.groupBox_2)
        self.spinbox_label_font_size.setMinimumSize(QtCore.QSize(70, 0))
        self.spinbox_label_font_size.setObjectName("spinbox_label_font_size")
        self.horizontalLayout_3.addWidget(self.spinbox_label_font_size)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.checkbox_use_label = QtGui.QCheckBox(self.groupBox_2)
        self.checkbox_use_label.setText("")
        self.checkbox_use_label.setChecked(True)
        self.checkbox_use_label.setObjectName("checkbox_use_label")
        self.horizontalLayout_4.addWidget(self.checkbox_use_label)
        self.label_label = QtGui.QLabel(self.groupBox_2)
        self.label_label.setObjectName("label_label")
        self.horizontalLayout_4.addWidget(self.label_label)
        self.line_label = QtGui.QLineEdit(self.groupBox_2)
        self.line_label.setObjectName("line_label")
        self.horizontalLayout_4.addWidget(self.line_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        self.button_color = QtGui.QPushButton(self.groupBox_2)
        self.button_color.setObjectName("button_color")
        self.horizontalLayout_12.addWidget(self.button_color)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "partition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Position ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "×", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "LineLength ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "LineWidth ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Style ", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_style.setItemText(0, QtGui.QApplication.translate("Form", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_style.setItemText(1, QtGui.QApplication.translate("Form", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Label Font Size ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_label.setText(QtGui.QApplication.translate("Form", "Label ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.button_color.setText(QtGui.QApplication.translate("Form", "SelectColor", None, QtGui.QApplication.UnicodeUTF8))

