# -*- coding: utf-8 -*-
try:
  from PySide2.QtCore import * 
  from PySide2.QtGui import * 
  from PySide2.QtWidgets import *
  from PySide2 import __version__
except ImportError:
  from PySide.QtCore import * 
  from PySide.QtGui import * 
  from PySide import __version__

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(504, 611)
        Form.setMinimumSize(QSize(0, 0))
        self.gridLayout = QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonbox = QDialogButtonBox(Form)
        self.buttonbox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.buttonbox.setObjectName("buttonbox")
        self.gridLayout.addWidget(self.buttonbox, 1, 0, 1, 1)
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_ScriptCommands = QGroupBox(Form)
        self.groupBox_ScriptCommands.setObjectName("groupBox_ScriptCommands")
        self.gridLayout_2 = QGridLayout(self.groupBox_ScriptCommands)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_script_language = QLabel(self.groupBox_ScriptCommands)
        self.label_script_language.setObjectName("label_script_language")
        self.horizontalLayout.addWidget(self.label_script_language)
        self.combo_script_language = QComboBox(self.groupBox_ScriptCommands)
        self.combo_script_language.setObjectName("combo_script_language")
        self.combo_script_language.addItem("")
        self.combo_script_language.addItem("")
        self.horizontalLayout.addWidget(self.combo_script_language)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.text_script_code = QTextEdit(self.groupBox_ScriptCommands)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_script_code.sizePolicy().hasHeightForWidth())
        self.text_script_code.setSizePolicy(sizePolicy)
        self.text_script_code.setLineWrapMode(QTextEdit.NoWrap)
        self.text_script_code.setObjectName("text_script_code")
        self.verticalLayout_4.addWidget(self.text_script_code)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkbox_externalfile = QCheckBox(self.groupBox_ScriptCommands)
        self.checkbox_externalfile.setObjectName("checkbox_externalfile")
        self.horizontalLayout_10.addWidget(self.checkbox_externalfile)
        self.line_externalfile = QLineEdit(self.groupBox_ScriptCommands)
        self.line_externalfile.setObjectName("line_externalfile")
        self.horizontalLayout_10.addWidget(self.line_externalfile)
        self.button_externalfile = QToolButton(self.groupBox_ScriptCommands)
        self.button_externalfile.setObjectName("button_externalfile")
        self.horizontalLayout_10.addWidget(self.button_externalfile)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_ScriptCommands)
        self.groupBox_2 = QGroupBox(Form)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.button_preview = QHBoxLayout()
        self.button_preview.setObjectName("button_preview")
        self.horizontalLayout_9.addLayout(self.button_preview)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinbox_btn_position_x = QSpinBox(self.groupBox_2)
        self.spinbox_btn_position_x.setMinimumSize(QSize(70, 0))
        self.spinbox_btn_position_x.setMaximumSize(QSize(16777215, 16777215))
        self.spinbox_btn_position_x.setMaximum(9999)
        self.spinbox_btn_position_x.setObjectName("spinbox_btn_position_x")
        self.horizontalLayout_5.addWidget(self.spinbox_btn_position_x)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinbox_btn_position_y = QSpinBox(self.groupBox_2)
        self.spinbox_btn_position_y.setMinimumSize(QSize(70, 0))
        self.spinbox_btn_position_y.setMaximum(9999)
        self.spinbox_btn_position_y.setObjectName("spinbox_btn_position_y")
        self.horizontalLayout_5.addWidget(self.spinbox_btn_position_y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.checkbox_fix_size = QCheckBox(self.groupBox_2)
        self.checkbox_fix_size.setObjectName("checkbox_fix_size")
        self.horizontalLayout_2.addWidget(self.checkbox_fix_size)
        self.spinbox_width = QSpinBox(self.groupBox_2)
        self.spinbox_width.setMinimumSize(QSize(70, 0))
        self.spinbox_width.setMaximum(9999)
        self.spinbox_width.setObjectName("spinbox_width")
        self.horizontalLayout_2.addWidget(self.spinbox_width)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinbox_height = QSpinBox(self.groupBox_2)
        self.spinbox_height.setMinimumSize(QSize(70, 0))
        self.spinbox_height.setMaximum(9999)
        self.spinbox_height.setObjectName("spinbox_height")
        self.horizontalLayout_2.addWidget(self.spinbox_height)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinbox_label_font_size = QSpinBox(self.groupBox_2)
        self.spinbox_label_font_size.setMinimumSize(QSize(70, 0))
        self.spinbox_label_font_size.setObjectName("spinbox_label_font_size")
        self.horizontalLayout_3.addWidget(self.spinbox_label_font_size)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.checkbox_use_label = QCheckBox(self.groupBox_2)
        self.checkbox_use_label.setText("")
        self.checkbox_use_label.setChecked(True)
        self.checkbox_use_label.setObjectName("checkbox_use_label")
        self.horizontalLayout_4.addWidget(self.checkbox_use_label)
        self.label_label = QLabel(self.groupBox_2)
        self.label_label.setObjectName("label_label")
        self.horizontalLayout_4.addWidget(self.label_label)
        self.text_label = QTextEdit(self.groupBox_2)
        self.text_label.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_label.sizePolicy().hasHeightForWidth())
        self.text_label.setSizePolicy(sizePolicy)
        self.text_label.setMaximumSize(QSize(160, 50))
        self.text_label.setObjectName("text_label")
        self.horizontalLayout_4.addWidget(self.text_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_tooltip = QTextEdit(self.groupBox_2)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_tooltip.sizePolicy().hasHeightForWidth())
        self.text_tooltip.setSizePolicy(sizePolicy)
        self.text_tooltip.setMaximumSize(QSize(160, 30))
        self.text_tooltip.setObjectName("text_tooltip")
        self.verticalLayout_3.addWidget(self.text_tooltip)
        self.checkbox_tooltip = QCheckBox(self.groupBox_2)
        self.checkbox_tooltip.setChecked(True)
        self.checkbox_tooltip.setObjectName("checkbox_tooltip")
        self.verticalLayout_3.addWidget(self.checkbox_tooltip)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.checkbox_bgcolor = QCheckBox(self.groupBox_2)
        self.checkbox_bgcolor.setObjectName("checkbox_bgcolor")
        self.horizontalLayout_12.addWidget(self.checkbox_bgcolor)
        self.button_bgcolor = QPushButton(self.groupBox_2)
        self.button_bgcolor.setObjectName("button_bgcolor")
        self.horizontalLayout_12.addWidget(self.button_bgcolor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QGroupBox(Form)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QGridLayout(self.groupBox)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.line_icon_file = QLineEdit(self.groupBox)
        self.line_icon_file.setObjectName("line_icon_file")
        self.horizontalLayout_8.addWidget(self.line_icon_file)
        self.button_icon = QToolButton(self.groupBox)
        self.button_icon.setObjectName("button_icon")
        self.horizontalLayout_8.addWidget(self.button_icon)
        self.button_maya_icon = QToolButton(self.groupBox)
        self.button_maya_icon.setText("")
        self.button_maya_icon.setAutoRaise(True)
        self.button_maya_icon.setObjectName("button_maya_icon")
        self.horizontalLayout_8.addWidget(self.button_maya_icon)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkbox_use_icon = QCheckBox(self.groupBox)
        self.checkbox_use_icon.setObjectName("checkbox_use_icon")
        self.horizontalLayout_11.addWidget(self.checkbox_use_icon)
        spacerItem7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.combo_icon_style = QComboBox(self.groupBox)
        self.combo_icon_style.setObjectName("combo_icon_style")
        self.combo_icon_style.addItem("")
        self.combo_icon_style.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_icon_style)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.spinbox_icon_size = QSpinBox(self.groupBox)
        self.spinbox_icon_size.setMinimumSize(QSize(70, 0))
        self.spinbox_icon_size.setMaximum(9999)
        self.spinbox_icon_size.setObjectName("spinbox_icon_size")
        self.horizontalLayout_11.addWidget(self.spinbox_icon_size)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QApplication.translate("Form", "Form", None, QApplication.UnicodeUTF8))
        self.groupBox_ScriptCommands.setTitle(QApplication.translate("Form", "Script Commands", None, QApplication.UnicodeUTF8))
        self.label_script_language.setText(QApplication.translate("Form", "Scripting Language", None, QApplication.UnicodeUTF8))
        self.combo_script_language.setItemText(0, QApplication.translate("Form", "MEL", None, QApplication.UnicodeUTF8))
        self.combo_script_language.setItemText(1, QApplication.translate("Form", "Python", None, QApplication.UnicodeUTF8))
        self.checkbox_externalfile.setText(QApplication.translate("Form", "External File", None, QApplication.UnicodeUTF8))
        self.button_externalfile.setText(QApplication.translate("Form", "...", None, QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QApplication.translate("Form", "Button", None, QApplication.UnicodeUTF8))
        self.label_7.setText(QApplication.translate("Form", "Position ", None, QApplication.UnicodeUTF8))
        self.label_6.setText(QApplication.translate("Form", "×", None, QApplication.UnicodeUTF8))
        self.checkbox_fix_size.setText(QApplication.translate("Form", "FixSize", None, QApplication.UnicodeUTF8))
        self.label_3.setText(QApplication.translate("Form", "×", None, QApplication.UnicodeUTF8))
        self.label_4.setText(QApplication.translate("Form", "Label Font Size ", None, QApplication.UnicodeUTF8))
        self.label_label.setText(QApplication.translate("Form", "Label ", None, QApplication.UnicodeUTF8))
        self.text_label.setHtml(QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS UI Gothic\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Button</p></body></html>", None, QApplication.UnicodeUTF8))
        self.label.setText(QApplication.translate("Form", "Tooltip ", None, QApplication.UnicodeUTF8))
        self.checkbox_tooltip.setText(QApplication.translate("Form", "Same as code", None, QApplication.UnicodeUTF8))
        self.checkbox_bgcolor.setText(QApplication.translate("Form", "BackgroundColor", None, QApplication.UnicodeUTF8))
        self.button_bgcolor.setText(QApplication.translate("Form", "SelectColor", None, QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QApplication.translate("Form", "Icon", None, QApplication.UnicodeUTF8))
        self.label_8.setText(QApplication.translate("Form", "File", None, QApplication.UnicodeUTF8))
        self.button_icon.setText(QApplication.translate("Form", "...", None, QApplication.UnicodeUTF8))
        self.checkbox_use_icon.setText(QApplication.translate("Form", "Use Icon", None, QApplication.UnicodeUTF8))
        self.label_5.setText(QApplication.translate("Form", "Style ", None, QApplication.UnicodeUTF8))
        self.combo_icon_style.setItemText(0, QApplication.translate("Form", "[ Icon ]Left  [ Label ]Right", None, QApplication.UnicodeUTF8))
        self.combo_icon_style.setItemText(1, QApplication.translate("Form", "[ Icon ]Up  [ Label ]Under", None, QApplication.UnicodeUTF8))
        self.label_2.setText(QApplication.translate("Form", " Size ", None, QApplication.UnicodeUTF8))

